In [1]:
import pandas as pd
import numpy as np
import math
from datetime import datetime, timedelta

In [2]:
data_dir = '../data/'

In [3]:
book1_sample = data_dir + 'book_level1_1_1665597600_1665619200.parquet'
trade_sample = data_dir + 'trade_exchange_1_1665597600_1665619200.parquet'

In [4]:
symbols = ['ADA-USD','XLM-USD','ALGO-USD','ZEC-USD','DOGE-USD','SHIB-USD','SUSHI-USD','EOS-USD','ETC-USD','WBTC-USD']

In [5]:
book1 = pd.read_parquet(book1_sample)
book1.head()

,ADA-USD:bids,ADA-USD:asks,ADA-USD:sequence,XLM-USD:bids,XLM-USD:asks,XLM-USD:sequence,ALGO-USD:bids,ALGO-USD:asks,ALGO-USD:sequence,ZEC-USD:bids,...,EOS-USD:asks,EOS-USD:sequence,ETC-USD:bids,ETC-USD:asks,ETC-USD:sequence,WBTC-USD:bids,WBTC-USD:asks,WBTC-USD:sequence,sequence_time,record_time
0,"[0.3867, 3361.12, 2.0]","[0.387, 22354.0, 4.0]",6605476049,"[0.115275, 2700.0, 1.0]","[0.115293, 8385.0, 1.0]",11118177866,"[0.312, 2000.0, 1.0]","[0.3123, 14860.8, 6.0]",6483895405,"[51.42, 58.18097, 2.0]",...,"[1.0341, 506.8, 1.0]",4062446594,"[23.73, 71.129, 2.0]","[23.75, 96.67224, 3.0]",7755736259,"[19043.08, 0.01487567, 1.0]","[19113.72, 0.00600918, 1.0]",2101824409,2022-10-12T18:00:00.000000 UTC,2022-10-12T18:00:00.000000 UTC
1,"[0.3867, 3361.12, 2.0]","[0.387, 3406.42, 3.0]",6605476148,"[0.115278, 5088.0, 1.0]","[0.115293, 8385.0, 1.0]",11118177960,"[0.312, 2864.2, 2.0]","[0.3123, 13996.6, 5.0]",6483895424,"[51.42, 58.19147, 3.0]",...,"[1.0343, 496.0, 1.0]",4062446649,"[23.74, 71.129, 2.0]","[23.76, 96.678764, 3.0]",7755736349,"[19043.08, 0.01487567, 1.0]","[19113.72, 0.00600918, 1.0]",2101824409,2022-10-12T18:00:01.000000 UTC,2022-10-12T18:00:01.000000 UTC
2,"[0.3867, 11131.93, 5.0]","[0.387, 2656.42, 2.0]",6605476205,"[0.115259, 2700.0, 1.0]","[0.115292, 2700.0, 1.0]",11118178152,"[0.312, 2864.2, 2.0]","[0.3123, 12997.1, 4.0]",6483895449,"[51.42, 58.19147, 3.0]",...,"[1.0343, 496.0, 1.0]",4062446653,"[23.73, 63.76876, 2.0]","[23.75, 96.678764, 3.0]",7755736401,"[19043.08, 0.01487567, 1.0]","[19113.72, 0.00600918, 1.0]",2101824409,2022-10-12T18:00:02.000000 UTC,2022-10-12T18:00:02.000000 UTC
3,"[0.3867, 9415.68, 4.0]","[0.387, 4574.63, 3.0]",6605476269,"[0.115266, 2700.0, 1.0]","[0.115293, 32080.0, 2.0]",11118178304,"[0.312, 2864.2, 2.0]","[0.3123, 12997.1, 4.0]",6483895452,"[51.42, 58.19147, 3.0]",...,"[1.0342, 972.5, 2.0]",4062446679,"[23.73, 71.129, 2.0]","[23.75, 108.66812, 4.0]",7755736538,"[19043.08, 0.01487567, 1.0]","[19113.72, 0.00600918, 1.0]",2101824409,2022-10-12T18:00:03.000000 UTC,2022-10-12T18:00:03.000000 UTC
4,"[0.3869, 6117.92, 3.0]","[0.3871, 4979.06, 2.0]",6605476466,"[0.115284, 2700.0, 1.0]","[0.115293, 31877.0, 2.0]",11118178482,"[0.3122, 9927.5, 4.0]","[0.3125, 65.3, 1.0]",6483895652,"[51.44, 58.18097, 2.0]",...,"[1.0351, 480.0, 1.0]",4062446813,"[23.74, 71.129, 2.0]","[23.76, 108.64802, 4.0]",7755736676,"[19049.4, 0.01487074, 1.0]","[19113.72, 0.00600918, 1.0]",2101824549,2022-10-12T18:00:04.000000 UTC,2022-10-12T18:00:04.000000 UTC

In [6]:
trade = pd.read_parquet(trade_sample)
trade

,pid,sequence_time,record_time,time,trade_id,price,size,side
0,ADA-USD,2022-10-12T18:00:00.000000 UTC,2022-10-12T18:00:00.000000 UTC,2022-10-12 17:59:59.237701,84353976,0.386500,19.61,buy
1,XLM-USD,2022-10-12T18:00:00.000000 UTC,2022-10-12T18:00:00.000000 UTC,2022-10-12 17:59:59.442813,77234705,0.115293,5155.00,sell
2,SHIB-USD,2022-10-12T18:00:00.000000 UTC,2022-10-12T18:00:00.000000 UTC,2022-10-12 17:59:56.024198,89312009,0.000010,889402.00,sell
3,SHIB-USD,2022-10-12T18:00:00.000000 UTC,2022-10-12T18:00:00.000000 UTC,2022-10-12 17:59:57.559601,89312010,0.000010,12606270.00,buy
4,SHIB-USD,2022-10-12T18:00:01.000000 UTC,2022-10-12T18:00:01.000000 UTC,2022-10-12 18:00:00.837625,89312011,0.000010,3434339.00,buy
...,...,...,...,...,...,...,...,...
48278,ADA-USD,2022-10-12T23:59:58.000000 UTC,2022-10-12T23:59:58.000000 UTC,2022-10-12 23:59:57.811272,84371292,0.381300,591.03,sell
48279,SHIB-USD,2022-10-12T23:59:58.000000 UTC,2022-10-12T23:59:58.000000 UTC,2022-10-12 23:59:57.094549,89322617,0.000010,291280.00,sell
48280,SHIB-USD,2022-10-12T23:59:58.000000 UTC,2022-10-12T23:59:58.000000 UTC,2022-10-12 23:59:57.401403,89322618,0.000010,1322835.00,sell
48281,ALGO-USD,2022-10-12T23:59:59.000000 UTC,2022-10-12T23:59:59.000000 UTC,2022-10-12 23:59:58.278666,58836464,0.313500,152.30,sell
48282,SHIB-USD,2022-10-12T23:59:59.000000 UTC,2022-10-12T23:59:59.000000 UTC,2022-10-12 23:59:58.423042,89322619,0.000010,882377.00,sell

In [7]:
#### create book data

In [8]:
bid_price = dict()
bid_size = dict()
ask_price = dict()
ask_size = dict()
for symbol in symbols:
    bid_price[symbol] = [l[0] for l in book1['{}:bids'.format(symbol)].tolist()]
    bid_size[symbol] = [l[1] for l in book1['{}:bids'.format(symbol)].tolist()]
    ask_price[symbol] = [l[0] for l in book1['{}:asks'.format(symbol)].tolist()]
    ask_size[symbol] = [l[1] for l in book1['{}:asks'.format(symbol)].tolist()]

In [9]:
#### check for NaN

In [10]:
for symbol in symbols:
    for p in bid_price[symbol]:
        if math.isnan(p):
            print("{} bid price has NaN".format(symbol))
            break
    for z in bid_size[symbol]:
        if math.isnan(z):
            print("{} bid size has NaN".format(symbol))
            break
    for p in ask_price[symbol]:
        if math.isnan(p):
            print("{} ask price has NaN".fomrat(symbol))
            break
    for z in ask_size[symbol]:
        if math.isnan(z):
            print("{} ask size has NaN".format(symbol))
            break

In [11]:
### Book Inbalance

In [12]:
def book_volume_inbalance(sym, idx):
    ge_bid_price = bid_price[sym][idx] >= bid_price[sym][idx-1]
    le_bid_price = bid_price[sym][idx] <= bid_price[sym][idx-1]
    ge_ask_price = ask_price[sym][idx] >= ask_price[sym][idx-1]
    le_ask_price = ask_price[sym][idx] <= ask_price[sym][idx-1]
    en = ge_bid_price * bid_size[sym][idx] - le_bid_price * bid_size[sym][idx-1] + \
         ge_ask_price * ask_size[sym][idx-1] - le_ask_price * ask_size[sym][idx]
    return en

In [13]:
book_inbalances = dict()
for sym in symbols:
    en = [book_volume_inbalance(sym, i) for i in range(1, len(bid_price[sym]))]
    book_inbalances[sym] = en

In [ ]:
### Book Return

In [22]:
book_returns = dict()

In [26]:
def wap(bid_price, ask_price, bid_size, ask_size):
    return (bid_price * ask_size + ask_price * bid_size) / (bid_size + ask_size)

In [27]:
def log_return(price1, price2):
    return math.log(price2 / price1)

In [28]:
for sym in symbols:
    waps = [wap(bp, ap, bz, az) for bp, ap, bz, az in zip(bid_price[sym], ask_price[sym], bid_size[sym], ask_size[sym])]
    lrs = [log_return(p1, p2) for p1, p2 in zip(waps[:-1], waps[1:])]
    book_returns[sym] = lrs

In [ ]:
### Book Realized Volatility

In [30]:
book_volatilities = dict()

In [33]:
def realized_volatility(best_bid_prices, best_ask_prices, best_bid_sizes, best_ask_sizes):
    prices = [wap(bp, ap, bz, az) for bp, ap, bz, az in zip(best_bid_prices, best_ask_prices, best_bid_sizes, best_ask_sizes)]
    returns = [log_return(p1, p2) for p1, p2 in zip(prices[:-1], prices[1:])]
    #TODO: should i divide by the size?
    volatility = math.sqrt(sum([r**2 for r in returns]))
    return volatility

In [34]:
for sym in symbols:
    book_volatilities[sym] = realized_volatility(bid_price[sym], ask_price[sym], bid_size[sym], ask_size[sym])

In [36]:
book_volatilities

{'ADA-USD': 0.015560933213244005,
 'XLM-USD': 0.011167696493745308,
 'ALGO-USD': 0.015460873990812009,
 'ZEC-USD': 0.0145670387961067,
 'DOGE-USD': 0.013027822981487918,
 'SHIB-USD': 0.009374545507002747,
 'SUSHI-USD': 0.027945474117626178,
 'EOS-USD': 0.014106288378035731,
 'ETC-USD': 0.014514755325800715,
 'WBTC-USD': 0.019680099870318497}

In [14]:
### Trade Prices and Sizes per second

In [15]:
datetime_format = "%Y-%m-%dT%H:%M:%S.%f %Z"

In [16]:
min_time = datetime.strptime(trade['sequence_time'].min(), datetime_format)
max_time = datetime.strptime(trade['sequence_time'].max(), datetime_format)
print("{},{}".format(min_time, max_time))

2022-10-12 18:00:00,2022-10-12 23:59:59

In [17]:
trade_sizes = dict()
trade_avg_prices = dict()

In [18]:
for symbol in symbols:
    start_time = min_time
    end_time = max_time
    size_lst = []
    avg_price_lst = []
    while start_time < end_time:
        next_time = start_time + timedelta(seconds=1)
        rows = trade.query('pid == "{}" and time >= "{}" and time < "{}"'.format(symbol, start_time, next_time))
        trade_size = rows['size'].tolist()
        trade_price = rows['price'].tolist()
        size_lst.append(sum(trade_size))
        if len(trade_price) == 0:
            avg_price_lst.append(float("nan"))
        else:
            avg_price_lst.append(sum([p * z for p, z in zip(trade_price, trade_size)]) / sum(trade_size))
        start_time = next_time
    trade_sizes[symbol] = size_lst
    trade_avg_prices[symbol] = avg_price_lst

In [ ]:
### Trade Return